### ISSUE TITLE
Update docs with how to start and create a station

### ISSUE THREAD

**Issue by seeReadCode** [galactics/space-command#7]
I am attempting to set this up and it appears the docs and man pages may be a bit out of date.

## 1. Quick start (draft)

```sh
wspace init
space tle celestrak fetch
```
That sets up a space and loads some satellites.

## 3. How to create a first station?

I can't get `space station create` to work.  Silently fails.  `space log` shows:

```
2023-06-08T11:17:12.006 :: space :: DEBUG :: === command 'station' failed with return code  2 ===
```

Example attempt

```sh
space station create FWS FortWorth 32 -97 207
```

**Comment by galactics** [comment]
Hello !

To add planets, you have to follow the explanations provided by ``space planet --help``. I noticed some minor problems that prevented the automated process (i.e. the fetch sub command) to work correctly in the current version. If you want a specific planet or moon to be handled, I would like to point you to the aa_summaries.txt file presents [here](https://naif.jpl.nasa.gov/pub/naif/generic_kernels/spk/planets/) or [here](https://naif.jpl.nasa.gov/pub/naif/generic_kernels/spk/satellites/). They will tell you which file to download in order to make it available in space-command.

As for station creation, I noticed a while ago that negative coordinate were not handled properly, but got around it by directly setting the station in the config file. This is obviously not optimal.

I just pushed two commits correcting both issues in the 'dev' branch.

On a general note, I agree that the documentation is lacking examples. I will try to take some time to correct this in the coming weeks.

Thanks !
